services:
  # 只保留 Node.js 后端服务
  - type: web
    name: photo-timeline-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: "/"
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
